sudo: false
dist: trusty
language: node_js
node_js:
  - "8.2.1"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH=$HOME/.yarn/bin:$PATH

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn test --coverage
  - yarn flow:check

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - codeclimate-test-reporter < coverage/**/lcov.info
